### ISSUE TITLE
d key not working

### ISSUE THREAD

**Issue by mattnedrich** [ahuth/raycast#2]
Cool project. The `d` key does not seem to be working in the demo.

**Comment by ahuth** [comment]
Thanks!

The `d` key seems to be working for me on OS X with Chrome. Are there any errors in the console, @mattnedrich?

**Comment by mattnedrich** [comment]
Interesting. I was also using Chrome on OS X, but I had the Vimium chrome plugin installed. That was swallowing my `d` keystrokes it seems. Problem was on my end - I'll close it.

**Comment by ahuth** [comment]
Ah, very interesting. Thanks!
